title: Paulo Bertanha
description: Técnico em Informática
site_title: "Portfolio - Paulo"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kallardian
email: paulobertanha03@gmail.com

# absolute or relative
profile_picture: assets/images/professional-profile.jpg

# Google Analytics ID
google_analytics:
